package com.example.codeclan.quiz.components;


import com.example.codeclan.quiz.models.Question;
import com.example.codeclan.quiz.models.Quiz;
import com.example.codeclan.quiz.models.User;
import com.example.codeclan.quiz.repositories.QuestionRepository;
import com.example.codeclan.quiz.repositories.QuizRepository;
import com.example.codeclan.quiz.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Component
public class DataLoader implements ApplicationRunner {
    @Autowired
    QuestionRepository questionRepository;
    @Autowired
    QuizRepository quizRepository;
    @Autowired
    UserRepository userRepository;

    public DataLoader() {
    }

    public void run(ApplicationArguments args) {

        userRepository.deleteAll();
        quizRepository.deleteAll();
        questionRepository.deleteAll();

        Question question1 = new Question("Mythology", "multiple", "hard", "Talos, the mythical giant bronze man, was the protector of which island?", "Crete");
        questionRepository.save(question1);
        question1.addIncorrectAnswer("Sardinia");
        question1.addIncorrectAnswer("Sicily");
        question1.addIncorrectAnswer("Cyprus");
        questionRepository.save(question1);

        Question question2 = new Question("Animals", "multiple", "medium", "A carnivorous animal eats flesh, what does a nucivorous animal eat?", "Nuts");
        questionRepository.save(question2);
        question2.addIncorrectAnswer("Nothing");
        question2.addIncorrectAnswer("Fruit");
        question2.addIncorrectAnswer("Seaweed");
        questionRepository.save(question2);

        Question question3 = new Question("Entertainment: Music", "multiple", "easy", "Who had a 1969 top 5 hit with the song \'A Boy Named Sue\'", "Johnny Cash");
        questionRepository.save(question3);
        question3.addIncorrectAnswer("Bob Dylan");
        question3.addIncorrectAnswer("Willie Nelson");
        question3.addIncorrectAnswer("Kris Kristofferson");
        questionRepository.save(question3);

        Question question4 = new Question("History", "boolean", "hard", "The Kingdom of Prussia briefly held land in Estonia.", "False");
        questionRepository.save(question4);
        question4.addIncorrectAnswer("True");
        questionRepository.save(question4);


        Question question5 = new Question("Science: Mathematics", "boolean", "medium", "The proof for the Chinese Remainder Theorem used in Number Theory was NOT developed by its first publisher, Sun Tzu.", "True");
        questionRepository.save(question5);
        question5.addIncorrectAnswer("False");
        questionRepository.save(question5);


        User peter = new User("Peter", "Kelly", "peter.kelly@codeclan.com", "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsouthernentrepreneurs.uk.com%2Fpeter-kelly%2F&psig=AOvVaw2IYSzWqn7QGIxsnIkfu-Yx&ust=1586612528394000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCICN9rT-3egCFQAAAAAdAAAAABAD");
        userRepository.save(peter);

        User jan = new User("Jan", "Jindra", "jan.jindra@codeclan.com", "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpjtpartners.com%2Fpeople%2Fpeter-kelly&psig=AOvVaw2IYSzWqn7QGIxsnIkfu-Yx&ust=1586612528394000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCICN9rT-3egCFQAAAAAdAAAAABAH");
        userRepository.save(peter);

        Quiz quizA = new Quiz("Peter\'s Quiz", 2, 0, peter);
        quizRepository.save(quizA);

        peter.addQuizToUser(quizA);
        jan.addQuizToUser(quizA);
        userRepository.save(peter);
        userRepository.save(jan);

        quizA.addQuestionToQuiz(question1);
        quizA.addQuestionToQuiz(question2);
        quizRepository.save(quizA);


        Question questionGN1=new Question( "General Knowledge",  "multiple",  "medium",  "What is the world's most expensive spice by weight?",  "Saffron");
        questionRepository.save(questionGN1);
        questionGN1.addIncorrectAnswer("Cinnamon");
        questionGN1.addIncorrectAnswer("Cardamom");
        questionGN1.addIncorrectAnswer("Vanilla");
        questionRepository.save(questionGN1);
        Question questionGN2=new Question( "General Knowledge",  "multiple",  "easy",  "Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?",  "Cabbage Patch Kids");
        questionRepository.save(questionGN2);
        questionGN2.addIncorrectAnswer("Transformers");
        questionGN2.addIncorrectAnswer("Care Bears");
        questionGN2.addIncorrectAnswer("Rubik's Cube");
        questionRepository.save(questionGN2);
        Question questionGN3=new Question( "General Knowledge",  "multiple",  "medium",  "Rolex is a company that specializes in what type of product?",  "Watches");
        questionRepository.save(questionGN3);
        questionGN3.addIncorrectAnswer("Cars");
        questionGN3.addIncorrectAnswer("Computers");
        questionGN3.addIncorrectAnswer("Sports equipment");
        questionRepository.save(questionGN3);
        Question questionGN4=new Question( "General Knowledge",  "multiple",  "easy",  "On a dartboard, what number is directly opposite No. 1?",  "19");
        questionRepository.save(questionGN4);
        questionGN4.addIncorrectAnswer("20");
        questionGN4.addIncorrectAnswer("12");
        questionGN4.addIncorrectAnswer("15");
        questionRepository.save(questionGN4);
        Question questionGN5=new Question( "General Knowledge",  "multiple",  "easy",  "Which American president appears on a one dollar bill?",  "George Washington");
        questionRepository.save(questionGN5);
        questionGN5.addIncorrectAnswer("Thomas Jefferson");
        questionGN5.addIncorrectAnswer("Abraham Lincoln");
        questionGN5.addIncorrectAnswer("Benjamin Franklin");
        questionRepository.save(questionGN5);
        Question questionGN6=new Question( "General Knowledge",  "multiple",  "hard",  "When was 'YouTube' founded?",  "February 14, 2005");
                questionRepository.save(questionGN6);
        questionGN6.addIncorrectAnswer("May 22, 2000");
        questionGN6.addIncorrectAnswer("September 12, 2002");
        questionGN6.addIncorrectAnswer("July 19, 2009");
        questionRepository.save(questionGN6);
        Question questionGN7=new Question( "General Knowledge",  "multiple",  "easy",  "Which one of the following rhythm games was made by Harmonix?",  "Rock Band");
        questionRepository.save(questionGN7);
        questionGN7.addIncorrectAnswer("Meat Beat Mania");
        questionGN7.addIncorrectAnswer("Guitar Hero Live");
        questionGN7.addIncorrectAnswer("Dance Dance Revolution");
        questionRepository.save(questionGN7);
        Question questionGN8=new Question( "General Knowledge",  "multiple",  "medium",  "What is a 'dakimakura'?",  "A body pillow");
        questionRepository.save(questionGN8);
        questionGN8.addIncorrectAnswer("A Chinese meal");
        questionGN8.addIncorrectAnswer("A yoga posture");
        questionGN8.addIncorrectAnswer("A word used to describe two people who truly love each other");
        questionRepository.save(questionGN8);
        Question questionGN9=new Question( "General Knowledge",  "multiple",  "easy",  "What type of animal was Harambe, who was shot after a child fell into it's enclosure at the Cincinnati Zoo?",  "Gorilla");
        questionRepository.save(questionGN9);
        questionGN9.addIncorrectAnswer("Tiger");
        questionGN9.addIncorrectAnswer("Panda");
        questionGN9.addIncorrectAnswer("Crocodile");
        questionRepository.save(questionGN9);
        Question questionGN10=new Question( "General Knowledge",  "multiple",  "easy",  "Which of these colours is NOT featured in the logo for Google?",  "Pink");
        questionRepository.save(questionGN10);
        questionGN10.addIncorrectAnswer("Yellow");
        questionGN10.addIncorrectAnswer("Blue");
        questionGN10.addIncorrectAnswer("Green");
        questionRepository.save(questionGN10);
        Question questionGN11=new Question( "General Knowledge",  "multiple",  "hard",  "How many calories are in a 355 ml can of Pepsi Cola?",  "150");
        questionRepository.save(questionGN11);
        questionGN11.addIncorrectAnswer("200");
        questionGN11.addIncorrectAnswer("100");
        questionGN11.addIncorrectAnswer("155");
        questionRepository.save(questionGN11);
        Question questionGN12=new Question( "General Knowledge",  "multiple",  "medium",  "What is the Portuguese word for 'Brazil'?",  "Brasil");
        questionRepository.save(questionGN12);
        questionGN12.addIncorrectAnswer("Brazil");
        questionGN12.addIncorrectAnswer("Brasilia");
        questionGN12.addIncorrectAnswer("Brasíl");
        questionRepository.save(questionGN12);
        Question questionGN13=new Question( "General Knowledge",  "multiple",  "medium",  "Apple co-founder Steve Jobs died from complications of which form of cancer?",  "Pancreatic");
        questionRepository.save(questionGN13);
        questionGN13.addIncorrectAnswer("Bone");
        questionGN13.addIncorrectAnswer("Liver");
        questionGN13.addIncorrectAnswer("Stomach");
        questionRepository.save(questionGN13);
        Question questionGN14=new Question( "General Knowledge",  "multiple",  "medium",  "Whose greyscale face is on the kappa emoticon on Twitch?",  "Josh DeSeno");
        questionRepository.save(questionGN14);
        questionGN14.addIncorrectAnswer("Justin DeSeno");
        questionGN14.addIncorrectAnswer("John DeSeno");
        questionGN14.addIncorrectAnswer("Jimmy DeSeno");
        questionRepository.save(questionGN14);
        Question questionGN15=new Question( "General Knowledge",  "multiple",  "easy",  "What company developed the vocaloid Hatsune Miku?",  "Crypton Future Media");
        questionRepository.save(questionGN15);
        questionGN15.addIncorrectAnswer("Sega");
        questionGN15.addIncorrectAnswer("Sony");
        questionGN15.addIncorrectAnswer("Yamaha Corporation");
        questionRepository.save(questionGN15);
        Question questionGN16=new Question( "General Knowledge",  "multiple",  "medium",  "Which country drives on the left side of the road?",  "Japan");
        questionRepository.save(questionGN16);
        questionGN16.addIncorrectAnswer("Germany");
        questionGN16.addIncorrectAnswer("Russia");
        questionGN16.addIncorrectAnswer("China");
        questionRepository.save(questionGN16);
        Question questionGN17=new Question( "General Knowledge",  "multiple",  "hard",  "Which church's interior in Vatican City was designed in 1503 by renaissance architects including Bramante, Michelangelo and Bernini?",  "St. Peter's Basilica");
        questionRepository.save(questionGN17);
        questionGN17.addIncorrectAnswer("Catania Cathedral");
        questionGN17.addIncorrectAnswer("St. Mark's Basilica");
        questionGN17.addIncorrectAnswer("The Duomo of Florence");
        questionRepository.save(questionGN17);
        Question questionGN18=new Question( "General Knowledge",  "multiple",  "hard",  "Located in Chile, El Teniente is the world's largest underground mine for what metal?",  "Copper");
        questionRepository.save(questionGN18);
        questionGN18.addIncorrectAnswer("Iron");
        questionGN18.addIncorrectAnswer("Nickel");
        questionGN18.addIncorrectAnswer("Silver");
        questionRepository.save(questionGN18);
        Question questionGN19=new Question( "General Knowledge",  "multiple",  "easy",  "What is the name of NASA's most famous space telescope?",  "Hubble Space Telescope");
        questionRepository.save(questionGN19);
        questionGN19.addIncorrectAnswer("Big Eye");
        questionGN19.addIncorrectAnswer("Death Star");
        questionGN19.addIncorrectAnswer("Millenium Falcon");
        questionRepository.save(questionGN19);
        Question questionGN20=new Question( "General Knowledge",  "multiple",  "easy",  "What are Panama hats made out of?",  "Straw");
        questionRepository.save(questionGN20);
        questionGN20.addIncorrectAnswer("Silk");
        questionGN20.addIncorrectAnswer("Hemp");
        questionGN20.addIncorrectAnswer("Flax");
        questionRepository.save(questionGN20);
        Question questionMY1=new Question( "Mythology",  "multiple",  "hard",  "According to Algonquian folklore, how does one transform into a Wendigo?",  "Participating in cannibalism.");
        questionRepository.save(questionMY1);
        questionMY1.addIncorrectAnswer("Excessive mutilation of animal corpses.");
        questionMY1.addIncorrectAnswer("Performing a ritual involving murder.");
        questionMY1.addIncorrectAnswer("Drinking the blood of many slain animals.");
        questionRepository.save(questionMY1);
        Question questionMY2=new Question( "Mythology",  "multiple",  "medium",  "The Hippogriff, not to be confused with the Griffon, is a magical creature with the front half of an eagle, and the back half of what?",  "A Horse");
        questionRepository.save(questionMY2);
        questionMY2.addIncorrectAnswer("A Dragon");
        questionMY2.addIncorrectAnswer("A Tiger");
        questionMY2.addIncorrectAnswer("A Lion");
        questionRepository.save(questionMY2);
        Question questionMY3=new Question( "Mythology",  "multiple",  "easy",  "Who in Greek mythology, who led the Argonauts in search of the Golden Fleece?",  "Jason");
        questionRepository.save(questionMY3);
        questionMY3.addIncorrectAnswer("Castor");
        questionMY3.addIncorrectAnswer("Daedalus");
        questionMY3.addIncorrectAnswer("Odysseus");
        questionRepository.save(questionMY3);
        Question questionMY4=new Question( "Mythology",  "multiple",  "medium",  "Who was the Roman god of fire?",    "Vulcan");
        questionRepository.save(questionMY4);
        questionMY4.addIncorrectAnswer("Apollo");
        questionMY4.addIncorrectAnswer("Jupiter");
        questionMY4.addIncorrectAnswer("Mercury");
        questionRepository.save(questionMY4);
        Question questionMY5=new Question( "Mythology",  "multiple",  "easy",  "This Greek goddess's name was chosen for the dwarf planet responsible for discord on Pluto's classification amongst astronomers.",  "Eris");
        questionRepository.save(questionMY5);
        questionMY5.addIncorrectAnswer("Charon");
        questionMY5.addIncorrectAnswer("Ceres");
        questionMY5.addIncorrectAnswer("Dysnomia");
        questionRepository.save(questionMY5);
        Question questionMY6=new Question( "Mythology",  "multiple",  "medium",  "In Greek Mythology, who killed Achilles?",  "Paris");
        questionRepository.save(questionMY6);
        questionMY6.addIncorrectAnswer("Hector");
        questionMY6.addIncorrectAnswer("Helen");
        questionMY6.addIncorrectAnswer("Pericles");
        questionRepository.save(questionMY6);
        Question questionMY7=new Question( "Mythology",  "multiple",  "easy",  "Which figure from Greek mythology traveled to the underworld to return his wife Eurydice to the land of the living?",  "Orpheus");
        questionRepository.save(questionMY7);
        questionMY7.addIncorrectAnswer("Hercules");
        questionMY7.addIncorrectAnswer("Perseus");
        questionMY7.addIncorrectAnswer("Daedalus");
        questionRepository.save(questionMY7);
        Question questionMY8=new Question( "Mythology",  "multiple",  "easy",  "In Greek mythology, who is the god of wine?",  "Dionysus");
        questionRepository.save(questionMY8);
        questionMY8.addIncorrectAnswer("Hephaestus");
        questionMY8.addIncorrectAnswer("Demeter");
        questionMY8.addIncorrectAnswer("Apollo");
        questionRepository.save(questionMY8);
        Question questionMY9=new Question( "Mythology",  "multiple",  "hard",  "Who is the Egyptian god of reproduction and lettuce?",  "Min");
        questionRepository.save(questionMY9);
        questionMY9.addIncorrectAnswer("Menu");
        questionMY9.addIncorrectAnswer("Mut");
        questionMY9.addIncorrectAnswer("Meret");
        questionRepository.save(questionMY9);
        Question questionMY10=new Question( "Mythology",  "multiple",  "medium",  "According to the Egyptian Myth of Osiris, who murdered Osiris?",  "Set");
        questionRepository.save(questionMY10);
        questionMY10.addIncorrectAnswer("Horus");
        questionMY10.addIncorrectAnswer("Ra");
        questionMY10.addIncorrectAnswer("Anhur");
        questionRepository.save(questionMY10);
        Question questionMY11=new Question( "Mythology",  "multiple",  "easy",  "Which of these mythological creatures is said to be half-man and half-horse?",  "Centaur");
        questionRepository.save(questionMY11);
        questionMY11.addIncorrectAnswer("Minotaur");
        questionMY11.addIncorrectAnswer("Pegasus");
        questionMY11.addIncorrectAnswer("Gorgon");
        questionRepository.save(questionMY11);
        Question questionMY12=new Question( "Mythology",  "multiple",  "medium",  "Which of the following is not one of the Greek Fates?",  "Narcissus");
        questionRepository.save(questionMY12);
        questionMY12.addIncorrectAnswer("Clotho");
        questionMY12.addIncorrectAnswer("Atropos");
        questionMY12.addIncorrectAnswer("Lachesis");
        questionRepository.save(questionMY12);
        Question questionMY13=new Question( "Mythology",  "multiple",  "medium",  "The Maori hold that which island nation was founded by Kupe, who discovered it under a long white cloud?",  "New Zealand");
        questionRepository.save(questionMY13);
        questionMY13.addIncorrectAnswer("Vanuatu");
        questionMY13.addIncorrectAnswer("Fiji");
        questionMY13.addIncorrectAnswer("Hawaii");
        questionRepository.save(questionMY13);
        Question questionMY14=new Question( "Mythology",  "multiple",  "easy",  "What mytological creatures have women's faces and vultures' bodies?",  "Harpies");
        questionRepository.save(questionMY14);
        questionMY14.addIncorrectAnswer("Mermaids");
        questionMY14.addIncorrectAnswer("Nymph");
        questionMY14.addIncorrectAnswer("Lilith");
        questionRepository.save(questionMY14);
        Question questionMY15=new Question( "Mythology",  "multiple",  "medium",  "Who is the god of war in Polynesian mythology?",  "'Oro");
        questionRepository.save(questionMY15);
        questionMY15.addIncorrectAnswer("Hina");
        questionMY15.addIncorrectAnswer("Kohara");
        questionMY15.addIncorrectAnswer("Māui");
        questionRepository.save(questionMY15);
        Question questionMY16=new Question( "Mythology",  "multiple",  "hard",  "What immense structure is referred to in Norse Mythology as the Yggdrasil.",  "Tree");
        questionRepository.save(questionMY16);
        questionMY16.addIncorrectAnswer("Mountain");
        questionMY16.addIncorrectAnswer("Temple");
        questionMY16.addIncorrectAnswer("Castle");
        questionRepository.save(questionMY16);
        Question questionMY17=new Question( "Mythology",  "multiple",  "easy",  "The Nike apparel and footwear brand takes it's name from the Greek goddess of what?",  "Victory");
        questionRepository.save(questionMY17);
        questionMY17.addIncorrectAnswer("Courage");
        questionMY17.addIncorrectAnswer("Strength");
        questionMY17.addIncorrectAnswer("Honor");
        questionRepository.save(questionMY17);
        Question questionMY18=new Question( "Mythology",  "multiple",  "hard",  "Which Norse God has a horse named Sleipnir?",  "Odin");
        questionRepository.save(questionMY18);
        questionMY18.addIncorrectAnswer("Thor");
        questionMY18.addIncorrectAnswer("Frigg");
        questionMY18.addIncorrectAnswer("Balder");
        questionRepository.save(questionMY18);
        Question questionMY19=new Question( "Mythology",  "multiple",  "medium",  "The Norse god Odin has two pet crows named 'Huginn' and 'Muninn'.  What do their names mean?",  "Thought & Memory");
        questionRepository.save(questionMY19);
        questionMY19.addIncorrectAnswer("Power & Peace");
        questionMY19.addIncorrectAnswer("War & Learning");
        questionMY19.addIncorrectAnswer("Sleeping & Waking");
        questionRepository.save(questionMY19);
        Question questionMY20=new Question( "Mythology",  "multiple",  "medium",  "What is the name of the first human being in Norse mythology?",  "Ask");
        questionRepository.save(questionMY20);
        questionMY20.addIncorrectAnswer("Asmund");
        questionMY20.addIncorrectAnswer("Ake");
        questionMY20.addIncorrectAnswer("Asger");
        questionRepository.save(questionMY20);
        Question questionSP1=new Question( "Sports",  "multiple",  "easy",  "Which of the following sports is not part of the triathlon?",  "Horse-Riding");
        questionRepository.save(questionSP1);
        questionSP1.addIncorrectAnswer("Cycling");
        questionSP1.addIncorrectAnswer("Swimming");
        questionSP1.addIncorrectAnswer("Running");
        questionRepository.save(questionSP1);
        Question questionSP2=new Question( "Sports",  "multiple",  "hard",  "How many times did Martina Navratilova win the Wimbledon Singles Championship?",  "Nine");
        questionRepository.save(questionSP2);
        questionSP2.addIncorrectAnswer("Ten");
        questionSP2.addIncorrectAnswer("Seven");
        questionSP2.addIncorrectAnswer("Eight");
        questionRepository.save(questionSP2);
        Question questionSP3=new Question( "Sports",  "multiple",  "medium",  "With which team did Michael Schumacher make his Formula One debut at the 1991 Belgian Grand Prix?",  "Jordan");
        questionRepository.save(questionSP3);
        questionSP3.addIncorrectAnswer("Benetton");
        questionSP3.addIncorrectAnswer("Ferrari");
        questionSP3.addIncorrectAnswer("Mercedes");
        questionRepository.save(questionSP3);
        Question questionSP4=new Question( "Sports",  "multiple",  "medium",  "Which German sportswear company's logo is the 'Formstripe'?",  "Puma");
        questionRepository.save(questionSP4);
        questionSP4.addIncorrectAnswer("Nike");
        questionSP4.addIncorrectAnswer("Adidas");
        questionSP4.addIncorrectAnswer("Reebok");
        questionRepository.save(questionSP4);
        Question questionSP5=new Question( "Sports",  "multiple",  "medium",  "Who was the British professional wrestler Shirley Crabtree better known as?",  "Big Daddy");
        questionRepository.save(questionSP5);
        questionSP5.addIncorrectAnswer("Giant Haystacks");
        questionSP5.addIncorrectAnswer("Kendo Nagasaki");
        questionSP5.addIncorrectAnswer("Masambula");
        questionRepository.save(questionSP5);
        Question questionSP6=new Question( "Sports",  "multiple",  "easy",  "Which English football club has the nickname 'The Foxes'?",  "Leicester City");
        questionRepository.save(questionSP6);
        questionSP6.addIncorrectAnswer("Northampton Town");
        questionSP6.addIncorrectAnswer("Bradford City");
        questionSP6.addIncorrectAnswer("West Bromwich Albion");
        questionRepository.save(questionSP6);
        Question questionSP7=new Question( "Sports",  "multiple",  "medium",  "Which nation hosted the FIFA World Cup in 2006?",  "Germany");
        questionRepository.save(questionSP7);
        questionSP7.addIncorrectAnswer("United Kingdom");
        questionSP7.addIncorrectAnswer("Brazil");
        questionSP7.addIncorrectAnswer("South Africa");
        questionRepository.save(questionSP7);
        Question questionSP8=new Question( "Sports",  "multiple",  "hard",  "Which male player won the gold medal of table tennis singles in 2016 Olympics Games?",  "Ma Long (China)");
        questionRepository.save(questionSP8);
        questionSP8.addIncorrectAnswer("Zhang Jike (China)");
        questionSP8.addIncorrectAnswer("Jun Mizutani (Japan)");
        questionSP8.addIncorrectAnswer("Vladimir Samsonov (Belarus)");
        questionRepository.save(questionSP8);
        Question questionSP9=new Question( "Sports",  "multiple",  "easy",  "Which team won 2014 FIFA World Cup in Brazil?",  "Germany");
        questionRepository.save(questionSP9);
        questionSP9.addIncorrectAnswer("Argentina");
        questionSP9.addIncorrectAnswer("Brazil");
        questionSP9.addIncorrectAnswer("Netherlands");
        questionRepository.save(questionSP9);
        Question questionSP10=new Question( "Sports",  "multiple",  "medium",  "Which of the following pitchers was named National League Rookie of the Year for the 2013 season?",  "Jose Fernandez");
        questionRepository.save(questionSP10);
        questionSP10.addIncorrectAnswer("Jacob deGrom");
        questionSP10.addIncorrectAnswer("Shelby Miller");
        questionSP10.addIncorrectAnswer("Matt Harvey");
        questionRepository.save(questionSP10);
        Question questionSP11=new Question( "Sports",  "multiple",  "easy",  "Which boxer was banned for taking a bite out of Evander Holyfield's ear in 1997?",  "Mike Tyson");
        questionRepository.save(questionSP11);
        questionSP11.addIncorrectAnswer("Roy Jones Jr.");
        questionSP11.addIncorrectAnswer("Evander Holyfield");
        questionSP11.addIncorrectAnswer("Lennox Lewis");
        questionRepository.save(questionSP11);
        Question questionSP12=new Question( "Sports",  "multiple",  "medium",  "How many French Open's did Bjorn Borg win?",  "6");
        questionRepository.save(questionSP12);
        questionSP12.addIncorrectAnswer("4");
        questionSP12.addIncorrectAnswer("9");
        questionSP12.addIncorrectAnswer("2");
        questionRepository.save(questionSP12);
        Question questionSP13=new Question( "Sports",  "multiple",  "easy",  "Which African American is in part responsible for integrating  Major League baseball?",  "Jackie Robinson");
        questionRepository.save(questionSP13);
        questionSP13.addIncorrectAnswer("Curt Flood");
        questionSP13.addIncorrectAnswer("Roy Campanella");
        questionSP13.addIncorrectAnswer("Satchell Paige");
        questionRepository.save(questionSP13);
        Question questionSP14=new Question( "Sports",  "multiple",  "medium",  "How many premier league trophies did Sir Alex Ferguson win during his time at Manchester United?",  "13");
        questionRepository.save(questionSP14);
        questionSP14.addIncorrectAnswer("11");
        questionSP14.addIncorrectAnswer("20");
        questionSP14.addIncorrectAnswer("22");
        questionRepository.save(questionSP14);
        Question questionSP15=new Question( "Sports",  "multiple",  "easy",  "What is the name of Manchester United's home stadium?",  "Old Trafford");
        questionRepository.save(questionSP15);
        questionSP15.addIncorrectAnswer("Anfield");
        questionSP15.addIncorrectAnswer("City of Manchester Stadium");
        questionSP15.addIncorrectAnswer("St James Park");
        questionRepository.save(questionSP15);
        Question questionSP16=new Question( "Sports",  "multiple",  "hard",  "Which player 'kung-fu kicked' a Crystal Palace fan in January 1995?",  "Eric Cantona");
        questionRepository.save(questionSP16);
        questionSP16.addIncorrectAnswer("David Seamen");
        questionSP16.addIncorrectAnswer("Ashley Cole");
        questionSP16.addIncorrectAnswer("Mark Hughes");
        questionRepository.save(questionSP16);
        Question questionSP17=new Question( "Sports",  "multiple",  "easy",  "Who won the premier league title in the 2015-2016 season following a fairy tale run?",  "Leicester City");
        questionRepository.save(questionSP17);
        questionSP17.addIncorrectAnswer("Tottenham Hotspur");
        questionSP17.addIncorrectAnswer("Watford");
        questionSP17.addIncorrectAnswer("Stoke City");
        questionRepository.save(questionSP17);
        Question questionSP18=new Question( "Sports",  "multiple",  "easy",  "When was the FC Schalke 04 founded?",  "1904");
        questionRepository.save(questionSP18);
        questionSP18.addIncorrectAnswer("1909");
        questionSP18.addIncorrectAnswer("2008");
        questionSP18.addIncorrectAnswer("1999");
        questionRepository.save(questionSP18);
        Question questionSP19=new Question( "Sports",  "multiple",  "medium",  "Who was the topscorer for England national football team?",  "Wayne Rooney");
        questionRepository.save(questionSP19);
        questionSP19.addIncorrectAnswer("David Beckham");
        questionSP19.addIncorrectAnswer("Steven Gerrard");
        questionSP19.addIncorrectAnswer("Michael Owen");
        questionRepository.save(questionSP19);
        Question questionSP20=new Question( "Sports",  "multiple",  "medium",  "Which Formula 1 driver switched teams in the middle of the 2017 season?",  "Carlos Sainz Jr.");
        questionRepository.save(questionSP20);
        questionSP20.addIncorrectAnswer("Daniil Kvyat");
        questionSP20.addIncorrectAnswer("Jolyon Palmer");
        questionSP20.addIncorrectAnswer("Rio Haryanto");
        questionRepository.save(questionSP20);
        Question questionGE1=new Question( "Geography",  "multiple",  "medium",  "What is the only country in the world with a flag that doesn't have four right angles?",  "Nepal");
        questionRepository.save(questionGE1);
        questionGE1.addIncorrectAnswer("Panama");
        questionGE1.addIncorrectAnswer("Angola");
        questionGE1.addIncorrectAnswer("Egypt");
        questionRepository.save(questionGE1);
        Question questionGE2=new Question( "Geography",  "multiple",  "medium",  "How many sovereign states are members of the United Nations?",  "195");
        questionRepository.save(questionGE2);
        questionGE2.addIncorrectAnswer("201");
        questionGE2.addIncorrectAnswer("153");
        questionGE2.addIncorrectAnswer("178");
        questionRepository.save(questionGE2);
        Question questionGE3=new Question( "Geography",  "multiple",  "hard",  "Which of these countries is NOT a part of the Asian continent?",  "Suriname");
        questionRepository.save(questionGE3);
        questionGE3.addIncorrectAnswer("Georgia");
        questionGE3.addIncorrectAnswer("Russia");
        questionGE3.addIncorrectAnswer("Singapore");
        questionRepository.save(questionGE3);
        Question questionGE4=new Question( "Geography",  "multiple",  "easy",  "All of the following are classified as Finno-Ugric languages EXCEPT?",  "Samoyedic");
        questionRepository.save(questionGE4);
        questionGE4.addIncorrectAnswer("Hungarian");
        questionGE4.addIncorrectAnswer("Finnish");
        questionGE4.addIncorrectAnswer("Estonian");
        questionRepository.save(questionGE4);
        Question questionGE5=new Question( "Geography",  "multiple",  "medium",  "Which of the following countries banned the use of personal genetic ancestry tests?",  "Germany");
        questionRepository.save(questionGE5);
        questionGE5.addIncorrectAnswer("Austria");
        questionGE5.addIncorrectAnswer("Canada");
        questionGE5.addIncorrectAnswer("Sweden");
        questionRepository.save(questionGE5);
        Question questionGE6=new Question( "Geography",  "multiple",  "easy",  "Which of the following languages does NOT use the Latin alphabet?",  "Georgian");
        questionRepository.save(questionGE6);
        questionGE6.addIncorrectAnswer("Turkish");
        questionGE6.addIncorrectAnswer("Swahili");
        questionGE6.addIncorrectAnswer("Vietnamese");
        questionRepository.save(questionGE6);
        Question questionGE7=new Question( "Geography",  "multiple",  "medium",  "The World Health Organization headquarters is located in which European country?",  "Switzerland");
        questionRepository.save(questionGE7);
        questionGE7.addIncorrectAnswer("United Kingdom");
        questionGE7.addIncorrectAnswer("France");
        questionGE7.addIncorrectAnswer("Belgium");
        questionRepository.save(questionGE7);
        Question questionGE8=new Question( "Geography",  "multiple",  "medium",  "What is the capital of the State of Washington, United States?",  "Olympia");
        questionRepository.save(questionGE8);
        questionGE8.addIncorrectAnswer("Washington D.C.");
        questionGE8.addIncorrectAnswer("Seattle");
        questionGE8.addIncorrectAnswer("Yukon");
        questionRepository.save(questionGE8);
        Question questionGE9=new Question( "Geography",  "multiple",  "easy",  "What is the nickname for the US state Delaware?",  "The First State");
        questionRepository.save(questionGE9);
        questionGE9.addIncorrectAnswer("The Fiftieth State");
        questionGE9.addIncorrectAnswer("The Second State");
        questionGE9.addIncorrectAnswer("The Sixteenth State");
        questionRepository.save(questionGE9);
        Question questionGE10=new Question( "Geography",  "multiple",  "hard",  "What is the most populous Muslim-majority nation in 2010?",  "Indonesia");
        questionRepository.save(questionGE10);
        questionGE10.addIncorrectAnswer("Saudi Arabia");
        questionGE10.addIncorrectAnswer("Iran");
        questionGE10.addIncorrectAnswer("Sudan");
        questionRepository.save(questionGE10);
        Question questionGE11=new Question( "Geography",  "multiple",  "easy",  "What is the name of the peninsula containing Spain and Portugal?",  "Iberian Peninsula");
        questionRepository.save(questionGE11);
        questionGE11.addIncorrectAnswer("European Peninsula");
        questionGE11.addIncorrectAnswer("Peloponnesian Peninsula");
        questionGE11.addIncorrectAnswer("Scandinavian Peninsula");
        questionRepository.save(questionGE11);
        Question questionGE12=new Question( "Geography",  "multiple",  "easy",  "What is the capital of the US State of New York?",  "Albany");
        questionRepository.save(questionGE12);
        questionGE12.addIncorrectAnswer("Buffalo");
        questionGE12.addIncorrectAnswer("New York");
        questionGE12.addIncorrectAnswer("Rochester");
        questionRepository.save(questionGE12);
        Question questionGE13=new Question( "Geography",  "multiple",  "easy",  "Harvard University is located in which city?",  "Cambridge");
        questionRepository.save(questionGE13);
        questionGE13.addIncorrectAnswer("Providence");
        questionGE13.addIncorrectAnswer("New York");
        questionGE13.addIncorrectAnswer("Washington D.C.");
        questionRepository.save(questionGE13);
        Question questionGE14=new Question( "Geography",  "multiple",  "medium",  "What is the capital of Belarus?",  "Minsk");
        questionRepository.save(questionGE14);
        questionGE14.addIncorrectAnswer("Warsaw");
        questionGE14.addIncorrectAnswer("Kiev");
        questionGE14.addIncorrectAnswer("Vilnius");
        questionRepository.save(questionGE14);
        Question questionGE15=new Question( "Geography",  "multiple",  "medium",  "How many timezones does Russia have?",  "11");
        questionRepository.save(questionGE15);
        questionGE15.addIncorrectAnswer("6");
        questionGE15.addIncorrectAnswer("24");
        questionGE15.addIncorrectAnswer("16");
        questionRepository.save(questionGE15);
        Question questionGE16=new Question( "Geography",  "multiple",  "medium",  "What is the highest mountain in the world?",  "Mt. Everest");
        questionRepository.save(questionGE16);
        questionGE16.addIncorrectAnswer("Mount Godwin Austen");
        questionGE16.addIncorrectAnswer("Kangchenjunga");
        questionGE16.addIncorrectAnswer("Annapurna");
        questionRepository.save(questionGE16);
        Question questionGE17=new Question( "Geography",  "multiple",  "easy",  "Which of the following countries has a flag featuring a yellow lion wielding a sword on a dark red background?",  "Sri Lanka");
        questionRepository.save(questionGE17);
        questionGE17.addIncorrectAnswer("Kiribati");
        questionGE17.addIncorrectAnswer("Scotland");
        questionGE17.addIncorrectAnswer("Bhutan");
        questionRepository.save(questionGE17);
        Question questionGE18=new Question( "Geography",  "multiple",  "easy",  "What is the capital of Scotland?",  "Edinburgh");
        questionRepository.save(questionGE18);
        questionGE18.addIncorrectAnswer("Glasgow");
        questionGE18.addIncorrectAnswer("Dundee");
        questionGE18.addIncorrectAnswer("London");
        questionRepository.save(questionGE18);
        Question questionGE19=new Question( "Geography",  "multiple",  "medium",  "Bridgetown is the capital of which island country in the Carribean?",  "Barbados");
        questionRepository.save(questionGE19);
        questionGE19.addIncorrectAnswer("Cuba");
        questionGE19.addIncorrectAnswer("Jamaica");
        questionGE19.addIncorrectAnswer("Dominica");
        questionRepository.save(questionGE19);
        Question questionGE20=new Question( "Geography",  "multiple",  "medium",  "What is the name of the only remaining Grand Duchy in the world ?",  "Luxembourg");
        questionRepository.save(questionGE20);
        questionGE20.addIncorrectAnswer("Montenegro");
        questionGE20.addIncorrectAnswer("Liechtenstein");
        questionGE20.addIncorrectAnswer("Andorra");
        questionRepository.save(questionGE20);
        Question questionHI1=new Question( "History",  "multiple",  "easy",  "Which one of these was not a beach landing site in the Invasion of Normandy?",  "Silver");
        questionRepository.save(questionHI1);
        questionHI1.addIncorrectAnswer("Gold");
        questionHI1.addIncorrectAnswer("Juno");
        questionHI1.addIncorrectAnswer("Sword");
        questionRepository.save(questionHI1);
        Question questionHI2=new Question( "History",  "multiple",  "medium",  "The Spitfire L.F. Mk IX had what engine?",  "Merlin 66");
        questionRepository.save(questionHI2);
        questionHI2.addIncorrectAnswer("Griffon 65");
        questionHI2.addIncorrectAnswer("Merlin 50");
        questionHI2.addIncorrectAnswer("Merlin X");
        questionRepository.save(questionHI2);
        Question questionHI3=new Question( "History",  "multiple",  "medium",  "In what year was the last natural case of smallpox documented?",  "1977");
        questionRepository.save(questionHI3);
        questionHI3.addIncorrectAnswer("1982");
        questionHI3.addIncorrectAnswer("1980");
        questionHI3.addIncorrectAnswer("1990");
        questionRepository.save(questionHI3);
        Question questionHI4=new Question( "History",  "multiple",  "medium",  "How old was Lyndon B. Johnson when he assumed the role of President of the United States?",  "55");
        questionRepository.save(questionHI4);
        questionHI4.addIncorrectAnswer("50");
        questionHI4.addIncorrectAnswer("60");
        questionHI4.addIncorrectAnswer("54");
        questionRepository.save(questionHI4);
        Question questionHI5=new Question( "History",  "multiple",  "medium",  "What year did the Battle of Agincourt take place?",  "1415");
        questionRepository.save(questionHI5);
        questionHI5.addIncorrectAnswer("1463");
        questionHI5.addIncorrectAnswer("1401");
        questionHI5.addIncorrectAnswer("1422");
        questionRepository.save(questionHI5);
        Question questionHI6=new Question( "History",  "multiple",  "hard",  "When did Canada leave the confederation to become their own nation?",  "July 1st, 1867");
        questionRepository.save(questionHI6);
        questionHI6.addIncorrectAnswer("July 1st");
        questionHI6.addIncorrectAnswer("July 1st");
        questionHI6.addIncorrectAnswer("July 1st, 1902");
        questionRepository.save(questionHI6);
        Question questionHI7=new Question( "History",  "multiple",  "hard",  "How many sonatas did Ludwig van Beethoven write?",  "32");
        questionRepository.save(questionHI7);
        questionHI7.addIncorrectAnswer("50");
        questionHI7.addIncorrectAnswer("31");
        questionHI7.addIncorrectAnswer("21");
        questionRepository.save(questionHI7);
        Question questionHI8=new Question( "History",  "multiple",  "medium",  "Which Nation DID NOT have a Colony in Modern-day America?",  "Portugal");
        questionRepository.save(questionHI8);
        questionHI8.addIncorrectAnswer("Spain");
        questionHI8.addIncorrectAnswer("Sweden");
        questionHI8.addIncorrectAnswer("Netherlands");
        questionRepository.save(questionHI8);
        Question questionHI9=new Question( "History",  "multiple",  "medium",  "Who is attributed credit for recording the epic poem The Odyssey?",  "Homer");
        questionRepository.save(questionHI9);
        questionHI9.addIncorrectAnswer("Aristotle");
        questionHI9.addIncorrectAnswer("Odysseus");
        questionHI9.addIncorrectAnswer("Socrates");
        questionRepository.save(questionHI9);
        Question questionHI10=new Question( "History",  "multiple",  "hard",  "What was the name of the German offensive operation in October 1941 to take Moscow before winter?",  "Operation Typhoon");
        questionRepository.save(questionHI10);
        questionHI10.addIncorrectAnswer("Operation Sunflower");
        questionHI10.addIncorrectAnswer("Operation Barbarossa");
        questionHI10.addIncorrectAnswer("Case Blue");
        questionRepository.save(questionHI10);
        Question questionHI11=new Question( "History",  "multiple",  "easy",  "How old was Adolf Hitler when he died?",  "56");
        questionRepository.save(questionHI11);
        questionHI11.addIncorrectAnswer("43");
        questionHI11.addIncorrectAnswer("65");
        questionHI11.addIncorrectAnswer("47");
        questionRepository.save(questionHI11);
        Question questionHI12=new Question( "History",  "multiple",  "easy",  "Which modern country is known as 'The Graveyard of Empires'?",  "Afghanistan");
        questionRepository.save(questionHI12);
        questionHI12.addIncorrectAnswer("China");
        questionHI12.addIncorrectAnswer("Iraq");
        questionHI12.addIncorrectAnswer("Russia");
        questionRepository.save(questionHI12);
        Question questionHI13=new Question( "History",  "multiple",  "medium",  "When did construction of the Suez Canal finish?",  "1869");
        questionRepository.save(questionHI13);
        questionHI13.addIncorrectAnswer("1859");
        questionHI13.addIncorrectAnswer("1860");
        questionHI13.addIncorrectAnswer("1850");
        questionRepository.save(questionHI13);
        Question questionHI14=new Question( "History",  "multiple",  "easy",  "Who led the Communist Revolution of Russia?",  "Vladimir Lenin");
        questionRepository.save(questionHI14);
        questionHI14.addIncorrectAnswer("Joseph Stalin");
        questionHI14.addIncorrectAnswer("Vladimir Putin");
        questionHI14.addIncorrectAnswer("Mikhail Gorbachev");
        questionRepository.save(questionHI14);
        Question questionHI15=new Question( "History",  "multiple",  "hard",  "Before the American colonies switched to the Gregorian calendar in 1752, on what date did their new year start?",  "March 25th");
        questionRepository.save(questionHI15);
        questionHI15.addIncorrectAnswer("June 1st");
        questionHI15.addIncorrectAnswer("September 25th");
        questionHI15.addIncorrectAnswer("December 1st");
        questionRepository.save(questionHI15);
        Question questionHI16=new Question( "History",  "multiple",  "medium",  "Who was the only US President to be elected four times?",  "Franklin Roosevelt");
        questionRepository.save(questionHI16);
        questionHI16.addIncorrectAnswer("Theodore Roosevelt");
        questionHI16.addIncorrectAnswer("George Washington");
        questionHI16.addIncorrectAnswer("Abraham Lincoln");
        questionRepository.save(questionHI16);
        Question questionHI17=new Question( "History",  "multiple",  "medium",  "In 1845, a series of wars named after which indigenous people began in New Zealand?",  "Māori");
        questionRepository.save(questionHI17);
        questionHI17.addIncorrectAnswer("Papuans");
        questionHI17.addIncorrectAnswer("Aborigines");
        questionHI17.addIncorrectAnswer("Polynesians");
        questionRepository.save(questionHI17);
        Question questionHI18=new Question( "History",  "multiple",  "medium",  "What was the name of the planned invasion of Japan towards the end of World War II?",  "Operation Downfall");
        questionRepository.save(questionHI18);
        questionHI18.addIncorrectAnswer("Operation Boarding Party");
        questionHI18.addIncorrectAnswer("Operation Ironclad");
        questionHI18.addIncorrectAnswer("Operation Aflame");
        questionRepository.save(questionHI18);
        Question questionHI19=new Question( "History",  "multiple",  "easy",  "In what year was the M1911 pistol designed?",  "1911");
        questionRepository.save(questionHI19);
        questionHI19.addIncorrectAnswer("1907");
        questionHI19.addIncorrectAnswer("1899");
        questionHI19.addIncorrectAnswer("1917");
        questionRepository.save(questionHI19);
        Question questionHI20=new Question( "History",  "multiple",  "medium",  "Which Louis was known as 'The Sun King of France'?",  "Louis XIV");
        questionRepository.save(questionHI20);
        questionHI20.addIncorrectAnswer("Louis XIII");
        questionHI20.addIncorrectAnswer("Louis XV");
        questionHI20.addIncorrectAnswer("Louis XVI");
        questionRepository.save(questionHI20);
        Question questionPO1=new Question( "Politics",  "multiple",  "easy",  "Whose 2016 presidential campaign slogan was 'Make America Great Again'?",  "Donald Trump");
        questionRepository.save(questionPO1);
        questionPO1.addIncorrectAnswer("Ted Cruz");
        questionPO1.addIncorrectAnswer("Marco Rubio");
        questionPO1.addIncorrectAnswer("Bernie Sanders");
        questionRepository.save(questionPO1);
        Question questionPO2=new Question( "Politics",  "multiple",  "medium",  "Who was the British Prime Minister at the outbreak of the Second World War?",  "Neville Chamberlain");
        questionRepository.save(questionPO2);
        questionPO2.addIncorrectAnswer("Clement Attlee");
        questionPO2.addIncorrectAnswer("Winston Churchill");
        questionPO2.addIncorrectAnswer("Stanley Baldwin");
        questionRepository.save(questionPO2);
        Question questionPO3=new Question( "Politics",  "multiple",  "medium",  "Which president erased the national debt of the United States?",  "Andrew Jackson");
        questionRepository.save(questionPO3);
        questionPO3.addIncorrectAnswer("Ronald Reagan");
        questionPO3.addIncorrectAnswer("John F. Kennedy");
        questionPO3.addIncorrectAnswer("Franklin Roosevelt");
        questionRepository.save(questionPO3);
        Question questionPO4=new Question( "Politics",  "multiple",  "medium",  "Who was the 40th President of the USA?",  "Ronald Reagan");
        questionRepository.save(questionPO4);
        questionPO4.addIncorrectAnswer("Jimmy Carter");
        questionPO4.addIncorrectAnswer("Bill Clinton");
        questionPO4.addIncorrectAnswer("Richard Nixon");
        questionRepository.save(questionPO4);
        Question questionPO5=new Question( "Politics",  "multiple",  "easy",  "Which of the following Pacific Islander countries is ruled by a constitutional monarchy?",  "Tonga");
        questionRepository.save(questionPO5);
        questionPO5.addIncorrectAnswer("Palau");
        questionPO5.addIncorrectAnswer("Fiji");
        questionPO5.addIncorrectAnswer("Kiribati");
        questionRepository.save(questionPO5);
        Question questionPO6=new Question( "Politics",  "multiple",  "hard",  "Which Native American tribe/nation requires at least one half blood quantum (equivalent to one parent) to be eligible for membership?",  "Yomba Shoshone Tribe");
        questionRepository.save(questionPO6);
        questionPO6.addIncorrectAnswer("Standing Rock Sioux Tribe");
        questionPO6.addIncorrectAnswer("Kiowa Tribe of Oklahoma");
        questionPO6.addIncorrectAnswer("Pawnee Nation of Oklahoma");
        questionRepository.save(questionPO6);
        Question questionPO7=new Question( "Politics",  "multiple",  "medium",  "The 2014 movie 'The Raid 2: Berandal' was mainly filmed in which Asian county?", "Indonesia");
        questionRepository.save(questionPO7);
        questionPO7.addIncorrectAnswer("Thailand");
        questionPO7.addIncorrectAnswer("Brunei");
        questionPO7.addIncorrectAnswer("Malaysia");
        questionRepository.save(questionPO7);
        Question questionPO8=new Question( "Politics",  "multiple",  "easy",  "According to the United States Constitution, how old must a person be to be elected President of the United States?",  "35");
        questionRepository.save(questionPO8);
        questionPO8.addIncorrectAnswer("30");
        questionPO8.addIncorrectAnswer("40");
        questionPO8.addIncorrectAnswer("45");
        questionRepository.save(questionPO8);
        Question questionPO9=new Question( "Politics",  "multiple",  "hard",  "'Yes, America Can!' was this United States politician's de facto campaign slogan in 2004.",  "George W. Bush");
        questionRepository.save(questionPO9);
        questionPO9.addIncorrectAnswer("John Kerry");
        questionPO9.addIncorrectAnswer("Barack Obama");
        questionPO9.addIncorrectAnswer("Al Gore");
        questionRepository.save(questionPO9);
        Question questionPO10=new Question( "Politics",  "multiple",  "hard",  "Which of the following United States senators is known for performing a 24-hour long filibuster?",  "Strom Thurmond");
        questionRepository.save(questionPO10);
        questionPO10.addIncorrectAnswer("Roy Blunt");
        questionPO10.addIncorrectAnswer("John Barrasso");
        questionPO10.addIncorrectAnswer("Chuck Schumer");
        questionRepository.save(questionPO10);
        Question questionPO11=new Question( "Politics",  "multiple",  "medium",  "Who was elected leader of the UK Labour Party in September 2015?",  "Jeremy Corbyn");
        questionRepository.save(questionPO11);
        questionPO11.addIncorrectAnswer("Ed Miliband");
        questionPO11.addIncorrectAnswer("David Cameron");
        questionPO11.addIncorrectAnswer("Theresa May");
        questionRepository.save(questionPO11);
        Question questionPO12=new Question( "Politics",  "multiple",  "medium",  "What is former United States President Bill Clinton's full name?",  "William Jefferson Clinton");
        questionRepository.save(questionPO12);
        questionPO12.addIncorrectAnswer("William Roosevelt Clinton");
        questionPO12.addIncorrectAnswer("William Truman Clinton");
        questionPO12.addIncorrectAnswer("William Lincoln Clinton");
        questionRepository.save(questionPO12);
        Question questionPO13=new Question( "Politics",  "multiple",  "medium",  "Before 2016, in which other year did Donald Trump run for President?",  "2000");
        questionRepository.save(questionPO13);
        questionPO13.addIncorrectAnswer("2012");
        questionPO13.addIncorrectAnswer("1988");
        questionPO13.addIncorrectAnswer("2008");
        questionRepository.save(questionPO13);
        Question questionPO14=new Question( "Politics",  "multiple",  "medium",  "In United States history, how many vice presidents did Franklin D. Roosevelt have during his time in office as president?",  "3");
        questionRepository.save(questionPO14);
        questionPO14.addIncorrectAnswer("1");
        questionPO14.addIncorrectAnswer("2");
        questionPO14.addIncorrectAnswer("0");
        questionRepository.save(questionPO14);
        Question questionPO15=new Question( "Politics",  "multiple",  "easy",  "Former United States President Bill Clinton famously played which instrument?",  "Saxophone");
        questionRepository.save(questionPO15);
        questionPO15.addIncorrectAnswer("Baritone horn");
        questionPO15.addIncorrectAnswer("Piano");
        questionPO15.addIncorrectAnswer("Violin");
        questionRepository.save(questionPO15);
        Question questionPO16=new Question( "Politics",  "multiple",  "hard",  "Which of these was an official candidate in the 2017 British General Election?",  "Lord Buckethead");
        questionRepository.save(questionPO16);
        questionPO16.addIncorrectAnswer("James Francis");
        questionPO16.addIncorrectAnswer("Robert Wimbledon");
        questionPO16.addIncorrectAnswer("Sir Crumpetsby");
        questionRepository.save(questionPO16);
        Question questionPO17=new Question( "Politics",  "multiple",  "medium",  "Who succeeded Joseph Stalin as General Secretary of the Communist Party of the Soviet Union?",  "Nikita Khrushchev");
        questionRepository.save(questionPO17);
        questionPO17.addIncorrectAnswer("Leonid Brezhnev");
        questionPO17.addIncorrectAnswer("Mikhail Gorbachev");
        questionPO17.addIncorrectAnswer("Boris Yeltsin");
        questionRepository.save(questionPO17);
        Question questionPO18=new Question( "Politics",  "multiple",  "hard",  "In June 2017, Saudi Arabia and Egypt broke off ties with which country over its supposed support for terrorism?",  "Qatar");
        questionRepository.save(questionPO18);
        questionPO18.addIncorrectAnswer("Bahrain");
        questionPO18.addIncorrectAnswer("United States of America");
        questionPO18.addIncorrectAnswer("Russia");
        questionRepository.save(questionPO18);
        Question questionPO19=new Question( "Politics",  "multiple",  "easy",  "Which former US president was nicknamed 'Teddy' after he refused to shoot a defenseless black bear?",  "Theodore Roosevelt");
        questionRepository.save(questionPO19);
        questionPO19.addIncorrectAnswer("Woodrow Wilson");
        questionPO19.addIncorrectAnswer("James F. Fielder");
        questionPO19.addIncorrectAnswer("Andrew Jackson");
        questionRepository.save(questionPO19);
        Question questionPO20=new Question( "Politics",  "multiple",  "hard",  "What year did the effort to deploy the Common Core State Standards (CCSS) in the US begin?",  "2009");
        questionRepository.save(questionPO20);
        questionPO20.addIncorrectAnswer("2012");
        questionPO20.addIncorrectAnswer("2006");
        questionPO20.addIncorrectAnswer("1997");
        questionRepository.save(questionPO20);
        Question questionAR1=new Question( "Art",  "multiple",  "easy",  "Who painted the Mona Lisa?",  "Leonardo da Vinci");
        questionRepository.save(questionAR1);
        questionAR1.addIncorrectAnswer("Pablo Picasso");
        questionAR1.addIncorrectAnswer("Claude Monet");
        questionAR1.addIncorrectAnswer("Vincent van Gogh");
        questionRepository.save(questionAR1);
        Question questionAR2=new Question( "Art",  "multiple",  "hard",  "Painter Piet Mondrian (1872 - 1944) was a part of what movement?",  "Neoplasticism");
        questionRepository.save(questionAR2);
        questionAR2.addIncorrectAnswer("Precisionism");
        questionAR2.addIncorrectAnswer("Cubism");
        questionAR2.addIncorrectAnswer("Impressionism");
        questionRepository.save(questionAR2);
        Question questionAR3=new Question( "Art",  "multiple",  "medium",  "Which time signature is commonly known as 'Cut Time?'",  "2/2");
        questionRepository.save(questionAR3);
        questionAR3.addIncorrectAnswer("4/4");
        questionAR3.addIncorrectAnswer("6/8");
        questionAR3.addIncorrectAnswer("43924");
        questionRepository.save(questionAR3);
        Question questionAR4=new Question( "Art",  "multiple",  "easy",  "Who painted the Sistine Chapel?",  "Michelangelo");
        questionRepository.save(questionAR4);
        questionAR4.addIncorrectAnswer("Leonardo da Vinci");
        questionAR4.addIncorrectAnswer("Pablo Picasso");
        questionAR4.addIncorrectAnswer("Raphael");
        questionRepository.save(questionAR4);
        Question questionAR5=new Question( "Art",  "multiple",  "hard",  "What French sculptor designed the Statue of Liberty? ",  "Frederic Auguste Bartholdi");
        questionRepository.save(questionAR5);
        questionAR5.addIncorrectAnswer("Jean-Leon Gerome");
        questionAR5.addIncorrectAnswer("Auguste Rodin");
        questionAR5.addIncorrectAnswer("Henri Matisse");
        questionRepository.save(questionAR5);
        Question questionAR6=new Question( "Art",  "multiple",  "medium",  "Which artist's studio was known as 'The Factory'?",  "Andy Warhol");
        questionRepository.save(questionAR6);
        questionAR6.addIncorrectAnswer("Roy Lichtenstein");
        questionAR6.addIncorrectAnswer("David Hockney");
        questionAR6.addIncorrectAnswer("Peter Blake");
        questionRepository.save(questionAR6);
        Question questionAR7=new Question( "Art",  "multiple",  "medium",  "What nationality was the surrealist painter Salvador Dali?",  "Spanish");
        questionRepository.save(questionAR7);
        questionAR7.addIncorrectAnswer("Italian");
        questionAR7.addIncorrectAnswer("French");
        questionAR7.addIncorrectAnswer("Portuguese");
        questionRepository.save(questionAR7);
        Question questionAR8=new Question( "Art",  "multiple",  "hard",  "Albrecht Durer's birthplace and place of death were in...",  "Nurnberg");
        questionRepository.save(questionAR8);
        questionAR8.addIncorrectAnswer("Augsburg");
        questionAR8.addIncorrectAnswer("Bamberg");
        questionAR8.addIncorrectAnswer("Berlin");
        questionRepository.save(questionAR8);
        Question questionAR9=new Question( "Art",  "multiple",  "hard",  "What year did Albrecht Durer create the painting 'The Young Hare'?",  "1502");
        questionRepository.save(questionAR9);
        questionAR9.addIncorrectAnswer("1702");
        questionAR9.addIncorrectAnswer("1402");
        questionAR9.addIncorrectAnswer("1602");
        questionRepository.save(questionAR9);
        Question questionAR10=new Question( "Art",  "multiple",  "hard",  "What year was the Mona Lisa finished?",  "1504");
        questionRepository.save(questionAR10);
        questionAR10.addIncorrectAnswer("1487");
        questionAR10.addIncorrectAnswer("1523");
        questionAR10.addIncorrectAnswer("1511");
        questionRepository.save(questionAR10);
        Question questionAR11=new Question( "Art",  "multiple",  "easy",  "Who painted 'Swans Reflecting Elephants', 'Sleep', and 'The Persistence of Memory'?",  "Salvador Dali");
        questionRepository.save(questionAR11);
        questionAR11.addIncorrectAnswer("Jackson Pollock");
        questionAR11.addIncorrectAnswer("Vincent van Gogh");
        questionAR11.addIncorrectAnswer("Edgar Degas");
        questionRepository.save(questionAR11);
        Question questionAR12=new Question( "Art",  "multiple",  "medium",  "Which one of these paintings is not by Caspar David Friedrich?",  "The Black Sea");
        questionRepository.save(questionAR12);
        questionAR12.addIncorrectAnswer("The Sea of Ice");
        questionAR12.addIncorrectAnswer("Wanderer above the Sea of Fog");
        questionAR12.addIncorrectAnswer("The Monk by the Sea");
        questionRepository.save(questionAR12);
        Question questionAR13=new Question( "Art",  "multiple",  "medium",  "Which of these are the name of a famous marker brand?",  "Copic");
        questionRepository.save(questionAR13);
        questionAR13.addIncorrectAnswer("Dopix");
        questionAR13.addIncorrectAnswer("Cofix");
        questionAR13.addIncorrectAnswer("Marx");
        questionRepository.save(questionAR13);
        Question questionAR14=new Question( "Art",  "multiple",  "medium",  "Which artist's style was to use small different colored dots to create a picture?",  "Georges Seurat");
        questionRepository.save(questionAR14);
        questionAR14.addIncorrectAnswer("Paul Cezanne");
        questionAR14.addIncorrectAnswer("Vincent Van Gogh");
        questionAR14.addIncorrectAnswer("Henri Rousseau");
        questionRepository.save(questionAR14);
        Question questionAR15=new Question( "Art",  "multiple",  "hard",  "Which of these is not an additional variation of the color purple?",  "Kobicha");
        questionRepository.save(questionAR15);
        questionAR15.addIncorrectAnswer("Byzantium");
        questionAR15.addIncorrectAnswer("Pomp and Power");
        questionAR15.addIncorrectAnswer("Palatinate");
        questionRepository.save(questionAR15);
        Question questionAR16=new Question( "Art",  "multiple",  "hard",  "How many paint and pastel versions of 'The Scream' is Norwegian painter Edvard Munch believed to have produced?",  "4");
        questionRepository.save(questionAR16);
        questionAR16.addIncorrectAnswer("1");
        questionAR16.addIncorrectAnswer("3");
        questionAR16.addIncorrectAnswer("2");
        questionRepository.save(questionAR16);
        Question questionAR17=new Question( "Art",  "multiple",  "medium",  "Who designed the Chupa Chups logo?",  "Salvador Dali");
        questionRepository.save(questionAR17);
        questionAR17.addIncorrectAnswer("Pablo Picasso");
        questionAR17.addIncorrectAnswer("Andy Warhol");
        questionAR17.addIncorrectAnswer("Vincent van Gogh");
        questionRepository.save(questionAR17);
        Question questionAR18=new Question( "Art",  "multiple",  "easy",  "Who painted The Starry Night?",  "Vincent van Gogh");
        questionRepository.save(questionAR18);
        questionAR18.addIncorrectAnswer("Pablo Picasso");
        questionAR18.addIncorrectAnswer("Leonardo da Vinci");
        questionAR18.addIncorrectAnswer("Michelangelo");
        questionRepository.save(questionAR18);
        Question questionAR19=new Question( "Art",  "multiple",  "easy",  "Which Van Gogh painting depicts the view from his asylum in Saint-Remy-de-Provence in southern France?",  "The Starry Night");
        questionRepository.save(questionAR19);
        questionAR19.addIncorrectAnswer("Wheatfields with Crows");
        questionAR19.addIncorrectAnswer("The Sower with Setting Sun");
        questionAR19.addIncorrectAnswer("The Church at Auvers");
        questionRepository.save(questionAR19);
        Question questionAR20=new Question( "Art",  "multiple",  "easy",  "Which painting was not made by Vincent Van Gogh?",  "The Ninth Wave");
        questionRepository.save(questionAR20);
        questionAR20.addIncorrectAnswer("Cafe Terrace at Night");
        questionAR20.addIncorrectAnswer("Bedroom In Arles");
        questionAR20.addIncorrectAnswer("Starry Night");
        questionRepository.save(questionAR20);
        Question questionCE1=new Question( "Celebrities",  "multiple",  "medium",  "Which actress's real name was Frances Ethel Gumm?",  "Judy Garland");
        questionRepository.save(questionCE1);
        questionCE1.addIncorrectAnswer("Doris Day");
        questionCE1.addIncorrectAnswer("Julie Andrews");
        questionCE1.addIncorrectAnswer("Marilyn Monroe");
        questionRepository.save(questionCE1);
        Question questionCE2=new Question( "Celebrities",  "multiple",  "medium",  "What is the real name of 'moot', founder of the imageboard 4chan?",  "Christopher Poole");
        questionRepository.save(questionCE2);
        questionCE2.addIncorrectAnswer("Mark Zuckerberg");
        questionCE2.addIncorrectAnswer("Allison Harvard");
        questionCE2.addIncorrectAnswer("Catie Wayne");
        questionRepository.save(questionCE2);
        Question questionCE3=new Question( "Celebrities",  "multiple",  "medium",  "Paul McCartney has always used his middle name. What is his real first name? ",  "James");
        questionRepository.save(questionCE3);
        questionCE3.addIncorrectAnswer("John");
        questionCE3.addIncorrectAnswer("Jack");
        questionCE3.addIncorrectAnswer("Justin");
        questionRepository.save(questionCE3);
        Question questionCE4=new Question( "Celebrities",  "multiple",  "easy",  "By what name is Carlos Estevez better known? ",  "Charlie Sheen");
        questionRepository.save(questionCE4);
        questionCE4.addIncorrectAnswer("Ricky Martin");
        questionCE4.addIncorrectAnswer("Bruno Mars");
        questionCE4.addIncorrectAnswer("Joaquin Phoenix");
        questionRepository.save(questionCE4);
        Question questionCE5=new Question( "Celebrities",  "multiple",  "easy",  "Which actress married Michael Douglas in 2000?",  "Catherine Zeta-Jones");
        questionRepository.save(questionCE5);
        questionCE5.addIncorrectAnswer("Ruth Jones");
        questionCE5.addIncorrectAnswer("Pam Ferris");
        questionCE5.addIncorrectAnswer("Sara Sugarman");
        questionRepository.save(questionCE5);
        Question questionCE6=new Question( "Celebrities",  "multiple",  "medium",  "Donald J. Trump's Middle Name is...",  "John");
        questionRepository.save(questionCE6);
        questionCE6.addIncorrectAnswer("Jeff");
        questionCE6.addIncorrectAnswer("Jerald");
        questionCE6.addIncorrectAnswer("Jason");
        questionRepository.save(questionCE6);
        Question questionCE7=new Question( "Celebrities",  "multiple",  "medium",  "What year did radio icon Howard Stern start a job at radio station WNBC?",  "1982");
        questionRepository.save(questionCE7);
        questionCE7.addIncorrectAnswer("1985");
        questionCE7.addIncorrectAnswer("1984");
        questionCE7.addIncorrectAnswer("1995");
        questionRepository.save(questionCE7);
        Question questionCE8=new Question( "Celebrities",  "multiple",  "medium",  "Which of these people is NOT a part of the Internet comedy group Mega64?",  "Jon Jafari");
        questionRepository.save(questionCE8);
        questionCE8.addIncorrectAnswer("Rocco Botte");
        questionCE8.addIncorrectAnswer("Derrick Acosta");
        questionCE8.addIncorrectAnswer("Shawn Chatfield");
        questionRepository.save(questionCE8);
        Question questionCE9=new Question( "Celebrities",  "multiple",  "easy",  "What does film maker Dan Bell typically focus his films on?",  "Abandoned Buildings and Dead Malls");
        questionRepository.save(questionCE9);
        questionCE9.addIncorrectAnswer("Historic Landmarks");
        questionCE9.addIncorrectAnswer("Action Films");
        questionCE9.addIncorrectAnswer("Documentaries ");
        questionRepository.save(questionCE9);
        Question questionCE10=new Question( "Celebrities",  "multiple",  "easy",  "What was the cause of Marilyn Monroes suicide?",  "Drug Overdose");
        questionRepository.save(questionCE10);
        questionCE10.addIncorrectAnswer("Knife Attack");
        questionCE10.addIncorrectAnswer("House Fire");
        questionCE10.addIncorrectAnswer("Gunshot");
        questionRepository.save(questionCE10);
        Question questionCE11=new Question( "Celebrities",  "multiple",  "hard",  "How tall is Tom Cruise?",  "5' 7''");
        questionRepository.save(questionCE11);
        questionCE11.addIncorrectAnswer("5' 9''");
        questionCE11.addIncorrectAnswer("5' 4''");
        questionCE11.addIncorrectAnswer("5' 5''");
        questionRepository.save(questionCE11);
        Question questionCE12=new Question( "Celebrities",  "multiple",  "medium",  "If he was still alive, in what year would Elvis Presley celebrate his 100th birthday?",  "2035");
        questionRepository.save(questionCE12);
        questionCE12.addIncorrectAnswer("2030");
        questionCE12.addIncorrectAnswer("2040");
        questionCE12.addIncorrectAnswer("2045");
        questionRepository.save(questionCE12);
        Question questionCE13=new Question( "Celebrities",  "multiple",  "medium",  "What was the name of Marilyn Monroe's first husband?",  "James Dougherty");
        questionRepository.save(questionCE13);
        questionCE13.addIncorrectAnswer("Joe Dimaggio");
        questionCE13.addIncorrectAnswer("Kirk Douglas");
        questionCE13.addIncorrectAnswer("Arthur Miller");
        questionRepository.save(questionCE13);
        Question questionCE14=new Question( "Celebrities",  "multiple",  "medium",  "Which radio personality calls himself 'The King of All Media'?",  "Howard Stern");
        questionRepository.save(questionCE14);
        questionCE14.addIncorrectAnswer("Rush Limbaugh");
        questionCE14.addIncorrectAnswer("Pete Tong");
        questionCE14.addIncorrectAnswer("Ryan Seacrest");
        questionRepository.save(questionCE14);
        Question questionCE15=new Question( "Celebrities",  "multiple",  "medium",  "Who out of these actresses is the youngest?",  "Kiernan Shipka");
        questionRepository.save(questionCE15);
        questionCE15.addIncorrectAnswer("Ariel Winter");
        questionCE15.addIncorrectAnswer("Emma Watson");
        questionCE15.addIncorrectAnswer("Bonnie Wright");
        questionRepository.save(questionCE15);
        Question questionCE16=new Question( "Celebrities",  "multiple",  "hard",  "The eccentric natural philosopher Tycho Brahe kept what as a pet?",  "Moose");
        questionRepository.save(questionCE16);
        questionCE16.addIncorrectAnswer("Dog");
        questionCE16.addIncorrectAnswer("Bear");
        questionCE16.addIncorrectAnswer("Goat");
        questionRepository.save(questionCE16);
        Question questionCE17=new Question( "Celebrities",  "multiple",  "medium",  "Who is 'James Rolfe' better known as?",  "The Angry Video Game Nerd");
        questionRepository.save(questionCE17);
        questionCE17.addIncorrectAnswer("TotalBiscuit");
        questionCE17.addIncorrectAnswer("PeanutButterGamer");
        questionCE17.addIncorrectAnswer("PewDiePie");
        questionRepository.save(questionCE17);
        Question questionCE18=new Question( "Celebrities",  "multiple",  "medium",  "Which American celebrity died in 1977 playing golf in La Moraleja, Madrid?",  "Bing Crosby");
        questionRepository.save(questionCE18);
        questionCE18.addIncorrectAnswer("Elvis Presley");
        questionCE18.addIncorrectAnswer("Charlie Chaplin");
        questionCE18.addIncorrectAnswer("Groucho Marx");
        questionRepository.save(questionCE18);
        Question questionCE19=new Question( "Celebrities",  "multiple",  "hard",  "Gabe Newell was born in which year?",  "1962 ");
        questionRepository.save(questionCE19);
        questionCE19.addIncorrectAnswer("1970");
        questionCE19.addIncorrectAnswer("1960");
        questionCE19.addIncorrectAnswer("1972");
        questionRepository.save(questionCE19);
        Question questionCE20=new Question( "Celebrities",  "multiple",  "hard",  "Billy Herrington is from which US state?",  "New York");
        questionRepository.save(questionCE20);
        questionCE20.addIncorrectAnswer("Arizona");
        questionCE20.addIncorrectAnswer("California");
        questionCE20.addIncorrectAnswer("Georgia");
        questionRepository.save(questionCE20);
        Question questionAN1=new Question( "Animals",  "multiple",  "hard",  "What was the name of the Ethiopian Wolf before they knew it was related to wolves?",  "Simien Jackel");
        questionRepository.save(questionAN1);
        questionAN1.addIncorrectAnswer("Ethiopian Coyote");
        questionAN1.addIncorrectAnswer("Amharic Fox");
        questionAN1.addIncorrectAnswer("Canis Simiensis");
        questionRepository.save(questionAN1);
        Question questionAN2=new Question( "Animals",  "multiple",  "medium",  "What are rhino's horn made of?",  "Keratin");
        questionRepository.save(questionAN2);
        questionAN2.addIncorrectAnswer("Bone");
        questionAN2.addIncorrectAnswer("Ivory");
        questionAN2.addIncorrectAnswer("Skin");
        questionRepository.save(questionAN2);
        Question questionAN3=new Question( "Animals",  "multiple",  "hard",  "What scientific suborder does the family Hyaenidae belong to?",  "Feliformia");
        questionRepository.save(questionAN3);
        questionAN3.addIncorrectAnswer("Haplorhini");
        questionAN3.addIncorrectAnswer("Caniformia");
        questionAN3.addIncorrectAnswer("Ciconiiformes");
        questionRepository.save(questionAN3);
        Question questionAN4=new Question( "Animals",  "multiple",  "hard",  "What scientific family does the Aardwolf belong to?",  "Hyaenidae");
        questionRepository.save(questionAN4);
        questionAN4.addIncorrectAnswer("Canidae");
        questionAN4.addIncorrectAnswer("Felidae");
        questionAN4.addIncorrectAnswer("Eupleridae");
        questionRepository.save(questionAN4);
        Question questionAN5=new Question( "Animals",  "multiple",  "easy",  "What do you call a baby bat?",  "Pup");
        questionRepository.save(questionAN5);
        questionAN5.addIncorrectAnswer("Cub");
        questionAN5.addIncorrectAnswer("Chick");
        questionAN5.addIncorrectAnswer("Kid");
        questionRepository.save(questionAN5);
        Question questionAN6=new Question( "Animals",  "multiple",  "hard",  "What is the scientific name of the cheetah?",  "Acinonyx jubatus");
        questionRepository.save(questionAN6);
        questionAN6.addIncorrectAnswer("Panthera onca");
        questionAN6.addIncorrectAnswer("Lynx rufus");
        questionAN6.addIncorrectAnswer("Felis catus");
        questionRepository.save(questionAN6);
        Question questionAN7=new Question( "Animals",  "multiple",  "hard",  "What is the scientific name of the Budgerigar?",  "Melopsittacus undulatus");
        questionRepository.save(questionAN7);
        questionAN7.addIncorrectAnswer("Nymphicus hollandicus");
        questionAN7.addIncorrectAnswer("Pyrrhura molinae");
        questionAN7.addIncorrectAnswer("Ara macao");
        questionRepository.save(questionAN7);
        Question questionAN8=new Question( "Animals",  "multiple",  "hard",  "Which of these animals is NOT a lizard?",  "Tuatara");
        questionRepository.save(questionAN8);
        questionAN8.addIncorrectAnswer("Komodo Dragon");
        questionAN8.addIncorrectAnswer("Gila Monster");
        questionAN8.addIncorrectAnswer("Green Iguana");
        questionRepository.save(questionAN8);
        Question questionAN9=new Question( "Animals",  "multiple",  "easy",  "What is Grumpy Cat's real name?",  "Tardar Sauce");
        questionRepository.save(questionAN9);
        questionAN9.addIncorrectAnswer("Sauce");
        questionAN9.addIncorrectAnswer("Minnie");
        questionAN9.addIncorrectAnswer("Broccoli");
        questionRepository.save(questionAN9);
        Question questionAN10=new Question( "Animals",  "multiple",  "medium",  "Which of these species is not extinct?",  "Komodo dragon");
        questionRepository.save(questionAN10);
        questionAN10.addIncorrectAnswer("Japanese sea lion");
        questionAN10.addIncorrectAnswer("Tasmanian tiger");
        questionAN10.addIncorrectAnswer("Saudi gazelle");
        questionRepository.save(questionAN10);
        Question questionAN11=new Question( "Animals",  "multiple",  "easy",  "Which class of animals are newts members of?",  "Amphibian");
        questionRepository.save(questionAN11);
        questionAN11.addIncorrectAnswer("Fish");
        questionAN11.addIncorrectAnswer("Reptiles");
        questionAN11.addIncorrectAnswer("Mammals");
        questionRepository.save(questionAN11);
        Question questionAN12=new Question( "Animals",  "multiple",  "hard",  "Unlike on most salamanders, this part of a newt is flat?",  "Tail");
        questionRepository.save(questionAN12);
        questionAN12.addIncorrectAnswer("Head");
        questionAN12.addIncorrectAnswer("Teeth");
        questionAN12.addIncorrectAnswer("Feet");
        questionRepository.save(questionAN12);
        Question questionAN13=new Question( "Animals",  "multiple",  "hard",  "Which species is a 'mountain chicken'?",  "Frog");
        questionRepository.save(questionAN13);
        questionAN13.addIncorrectAnswer("Chicken");
        questionAN13.addIncorrectAnswer("Horse");
        questionAN13.addIncorrectAnswer("Fly");
        questionRepository.save(questionAN13);
        Question questionAN14=new Question( "Animals",  "multiple",  "medium",  "The dish Fugu, is made from what family of fish?",  "Pufferfish");
        questionRepository.save(questionAN14);
        questionAN14.addIncorrectAnswer("Bass");
        questionAN14.addIncorrectAnswer("Salmon");
        questionAN14.addIncorrectAnswer("Mackerel");
        questionRepository.save(questionAN14);
        Question questionAN15=new Question( "Animals",  "multiple",  "easy",  "What is the collective noun for a group of crows?",  "Murder");
        questionRepository.save(questionAN15);
        questionAN15.addIncorrectAnswer("Pack");
        questionAN15.addIncorrectAnswer("Gaggle");
        questionAN15.addIncorrectAnswer("Herd");
        questionRepository.save(questionAN15);
        Question questionAN16=new Question( "Animals",  "multiple",  "hard",  "Which of the following is another name for the 'Poecilotheria Metallica Tarantula'?",  "Gooty");
        questionRepository.save(questionAN16);
        questionAN16.addIncorrectAnswer("Hopper");
        questionAN16.addIncorrectAnswer("Silver Stripe");
        questionAN16.addIncorrectAnswer("Woebegone");
        questionRepository.save(questionAN16);
        Question questionAN17=new Question( "Animals",  "multiple",  "easy",  "By definition, where does an abyssopelagic animal live?",  "At the bottom of the ocean");
        questionRepository.save(questionAN17);
        questionAN17.addIncorrectAnswer("In the desert");
        questionAN17.addIncorrectAnswer("On top of a mountain");
        questionAN17.addIncorrectAnswer("Inside a tree");
        questionRepository.save(questionAN17);
        Question questionAN18=new Question( "Animals",  "multiple",  "hard",  "Which of these is a colony of polyps and not a jellyfish?",  "Portuguese Man-of-War");
        questionRepository.save(questionAN18);
        questionAN18.addIncorrectAnswer("Sea Wasp");
        questionAN18.addIncorrectAnswer("Irukandji");
        questionAN18.addIncorrectAnswer("Sea Nettle");
        questionRepository.save(questionAN18);
        Question questionAN19=new Question( "Animals",  "multiple",  "medium",  "What is the common term for bovine spongiform encephalopathy (BSE)?",  "Mad Cow disease");
        questionRepository.save(questionAN19);
        questionAN19.addIncorrectAnswer("Weil's disease");
        questionAN19.addIncorrectAnswer("Milk fever");
        questionAN19.addIncorrectAnswer("Foot-and-mouth disease");
        questionRepository.save(questionAN19);
        Question questionAN20=new Question( "Animals",  "multiple",  "medium",  "What is the collective noun for bears?",  "Sloth");
        questionRepository.save(questionAN20);
        questionAN20.addIncorrectAnswer("Drove");
        questionAN20.addIncorrectAnswer("Tribe");
        questionAN20.addIncorrectAnswer("Husk");
        questionRepository.save(questionAN20);
        Question questionVE1=new Question( "Vehicles",  "multiple",  "hard",  "What was the name of the first front-wheel-drive car produced by Datsun (now Nissan)?",  "Cherry");
        questionRepository.save(questionVE1);
        questionVE1.addIncorrectAnswer("Sunny");
        questionVE1.addIncorrectAnswer("Bluebird");
        questionVE1.addIncorrectAnswer("Skyline");
        questionRepository.save(questionVE1);
        Question questionVE2=new Question( "Vehicles",  "multiple",  "medium",  "Which animal features on the logo for Abarth, the motorsport division of Fiat?",  "Scorpion");
        questionRepository.save(questionVE2);
        questionVE2.addIncorrectAnswer("Snake");
        questionVE2.addIncorrectAnswer("Bull");
        questionVE2.addIncorrectAnswer("Horse");
        questionRepository.save(questionVE2);
        Question questionVE3=new Question( "Vehicles",  "multiple",  "easy",  "Which of the following car manufacturers had a war named after it?",  "Toyota");
        questionRepository.save(questionVE3);
        questionVE3.addIncorrectAnswer("Honda");
        questionVE3.addIncorrectAnswer("Ford");
        questionVE3.addIncorrectAnswer("Volkswagen");
        questionRepository.save(questionVE3);
        Question questionVE4=new Question( "Vehicles",  "multiple",  "easy",  "Which of the following collision avoidance systems helps airplanes avoid colliding with each other?",  "TCAS");
        questionRepository.save(questionVE4);
        questionVE4.addIncorrectAnswer("GPWS");
        questionVE4.addIncorrectAnswer("OCAS");
        questionVE4.addIncorrectAnswer("TAWS");
        questionRepository.save(questionVE4);
        Question questionVE5=new Question( "Vehicles",  "multiple",  "easy",  "Which of these companies does NOT manufacture motorcycles?",  "Toyota");
        questionRepository.save(questionVE5);
        questionVE5.addIncorrectAnswer("Honda");
        questionVE5.addIncorrectAnswer("Kawasaki");
        questionVE5.addIncorrectAnswer("Yamaha");
        questionRepository.save(questionVE5);
        Question questionVE6=new Question( "Vehicles",  "multiple",  "medium",  "Which supercar company is from Sweden?",  "Koenigsegg");
        questionRepository.save(questionVE6);
        questionVE6.addIncorrectAnswer("Bugatti");
        questionVE6.addIncorrectAnswer("Lamborghini");
        questionVE6.addIncorrectAnswer("McLaren");
        questionRepository.save(questionVE6);
        Question questionVE7=new Question( "Vehicles",  "multiple",  "medium",  "Which car brand does NOT belong to General Motors?",  "Ford");
        questionRepository.save(questionVE7);
        questionVE7.addIncorrectAnswer("Buick");
        questionVE7.addIncorrectAnswer("Cadillac");
        questionVE7.addIncorrectAnswer("Chevrolet");
        questionRepository.save(questionVE7);
        Question questionVE8=new Question( "Vehicles",  "multiple",  "medium",  "Which of these car models are produced by Lamborghini?",  "Aventador");
        questionRepository.save(questionVE8);
        questionVE8.addIncorrectAnswer("Huayra");
        questionVE8.addIncorrectAnswer("918");
        questionVE8.addIncorrectAnswer("Chiron");
        questionRepository.save(questionVE8);
        Question questionVE9=new Question( "Vehicles",  "multiple",  "hard",  "Which Variable Valve Timing technology is used by BMW?",  "VANOS");
        questionRepository.save(questionVE9);
        questionVE9.addIncorrectAnswer("VVT-iw");
        questionVE9.addIncorrectAnswer("VVEL");
        questionVE9.addIncorrectAnswer("MultiAir");
        questionRepository.save(questionVE9);
        Question questionVE10=new Question( "Vehicles",  "multiple",  "medium",  "What do the 4 Rings in Audi's Logo represent?",  "Previously independent automobile manufacturers");
        questionRepository.save(questionVE10);
        questionVE10.addIncorrectAnswer("States in which Audi makes the most sales");
        questionVE10.addIncorrectAnswer("Main cities vital to Audi");
        questionVE10.addIncorrectAnswer("Countries in which Audi makes the most sales");
        questionRepository.save(questionVE10);
        Question questionVE11=new Question( "Vehicles",  "multiple",  "hard",  "How much horsepower is produced by the SD40-2 Locomotive?",  "3000");
                questionRepository.save(questionVE11);
        questionVE11.addIncorrectAnswer("3200");
        questionVE11.addIncorrectAnswer("2578");
        questionVE11.addIncorrectAnswer("2190");
        questionRepository.save(questionVE11);
        Question questionVE12=new Question( "Vehicles",  "multiple",  "hard",  "What engine is in the Lexus SC400?",    "1UZ-FE");
        questionRepository.save(questionVE12);
        questionVE12.addIncorrectAnswer("2JZ-GTE");
        questionVE12.addIncorrectAnswer("7M-GTE");
        questionVE12.addIncorrectAnswer("5M-GE");
        questionRepository.save(questionVE12);
        Question questionVE13=new Question( "Vehicles",  "multiple",  "hard",  "Which one of the following is NOT a sub-company of the Volkswagen Group?",  "Opel");
        questionRepository.save(questionVE13);
        questionVE13.addIncorrectAnswer("Porsche");
        questionVE13.addIncorrectAnswer("Bugatti");
        questionVE13.addIncorrectAnswer("Bentley");
        questionRepository.save(questionVE13);
        Question questionVE14=new Question( "Vehicles",  "multiple",  "hard",  "In 2014, over 6 million General Motors vehicles were recalled due to what critical flaw?",  "Faulty ignition switch");
        questionRepository.save(questionVE14);
        questionVE14.addIncorrectAnswer("Malfunctioning gas pedal");
        questionVE14.addIncorrectAnswer("Breaking fuel lines");
        questionVE14.addIncorrectAnswer("Faulty brake pads");
        questionRepository.save(questionVE14);
        Question questionVE15=new Question( "Vehicles",  "multiple",  "hard",  "What model was the sports car gifted to Yuri Gagarin by the French government in 1965?",  "Matra Djet");
        questionRepository.save(questionVE15);
        questionVE15.addIncorrectAnswer("Porsche 911");
        questionVE15.addIncorrectAnswer("Alpine A110");
        questionVE15.addIncorrectAnswer("AC Cobra");
        questionRepository.save(questionVE15);
        Question questionVE16=new Question( "Vehicles",  "multiple",  "easy",  "The LS2 engine is how many cubic inches?",  "364");
        questionRepository.save(questionVE16);
        questionVE16.addIncorrectAnswer("346");
        questionVE16.addIncorrectAnswer("376");
        questionVE16.addIncorrectAnswer("402");
        questionRepository.save(questionVE16);
        Question questionVE17=new Question( "Vehicles",  "multiple",  "easy",  "The LS3 engine is how many cubic inches?",  "376");
        questionRepository.save(questionVE17);
        questionVE17.addIncorrectAnswer("346");
        questionVE17.addIncorrectAnswer("364");
        questionVE17.addIncorrectAnswer("427");
        questionRepository.save(questionVE17);
        Question questionVE18=new Question( "Vehicles",  "multiple",  "easy",  "What is the name of Nissan's most popular electric car?",  "Leaf");
        questionRepository.save(questionVE18);
        questionVE18.addIncorrectAnswer("Tree");
        questionVE18.addIncorrectAnswer("Deer");
        questionVE18.addIncorrectAnswer("Roots");
        questionRepository.save(questionVE18);
        Question questionVE19=new Question( "Vehicles",  "multiple",  "medium",  "Which car manufacturer created the 'Aventador'?",  "Lamborghini");
        questionRepository.save(questionVE19);
        questionVE19.addIncorrectAnswer("Ferrari");
        questionVE19.addIncorrectAnswer("Pagani");
        questionVE19.addIncorrectAnswer("Bugatti");
        questionRepository.save(questionVE19);
        Question questionVE20=new Question( "Vehicles",  "multiple",  "hard",  "Which Audi does not use Haldex based all wheel drive system?",  "Audi A8");
        questionRepository.save(questionVE20);
        questionVE20.addIncorrectAnswer("Audi TT");
        questionVE20.addIncorrectAnswer("Audi S3");
        questionVE20.addIncorrectAnswer("Audi A3");
        questionRepository.save(questionVE20);

        quizA.addQuestionToQuiz(questionVE20);
        quizA.addQuestionToQuiz(questionVE19);
        quizA.addQuestionToQuiz(questionVE18);
        quizA.addQuestionToQuiz(questionVE15);
        quizA.addQuestionToQuiz(question4);
        quizA.addQuestionToQuiz(question5);
        quizRepository.save(quizA);


        //Default Quiz
        User allQuestions = new User("Random", "Questions", "all@guestions.com", "https://lh3.googleusercontent.com/proxy/kJ34YbxDR9CVUvGynvJVVxb6LR2s-vrLBp79YlQRVaS1YG4vLalA53XdmxFDGl4S_TE1VynkVH2ROjluWXFqSux_-UAm_jSIIH0u-9fjeRGaJGIJkrtww8RfAvoe");
        userRepository.save(allQuestions);


        Quiz quizALL = new Quiz("Random Questions", 2, 2, allQuestions);
        quizRepository.save(quizALL);



        quizALL.addQuestionToQuiz(questionGN3);
        quizALL.addQuestionToQuiz(questionGN4);
        quizALL.addQuestionToQuiz(questionGN5);
        quizALL.addQuestionToQuiz(questionGN6);
        quizALL.addQuestionToQuiz(questionGN7);
        quizALL.addQuestionToQuiz(questionGN8);
        quizALL.addQuestionToQuiz(questionGN9);
        quizALL.addQuestionToQuiz(questionGN10);
        quizALL.addQuestionToQuiz(questionGN11);
        quizALL.addQuestionToQuiz(questionGN12);
        quizALL.addQuestionToQuiz(questionGN13);
        quizALL.addQuestionToQuiz(questionGN14);
        quizALL.addQuestionToQuiz(questionGN15);
        quizALL.addQuestionToQuiz(questionGN16);
        quizALL.addQuestionToQuiz(questionGN17);
        quizALL.addQuestionToQuiz(questionGN18);
        quizALL.addQuestionToQuiz(questionGN19);
        quizALL.addQuestionToQuiz(questionGN20);
        quizALL.addQuestionToQuiz(questionMY1);
        quizALL.addQuestionToQuiz(questionMY2);
        quizALL.addQuestionToQuiz(questionMY3);
        quizALL.addQuestionToQuiz(questionMY4);
        quizALL.addQuestionToQuiz(questionMY5);
        quizALL.addQuestionToQuiz(questionMY6);
        quizALL.addQuestionToQuiz(questionMY7);
        quizALL.addQuestionToQuiz(questionMY8);
        quizALL.addQuestionToQuiz(questionMY9);
        quizALL.addQuestionToQuiz(questionMY10);
        quizALL.addQuestionToQuiz(questionMY11);
        quizALL.addQuestionToQuiz(questionMY12);
        quizALL.addQuestionToQuiz(questionMY13);
        quizALL.addQuestionToQuiz(questionMY14);
        quizALL.addQuestionToQuiz(questionMY15);
        quizALL.addQuestionToQuiz(questionMY16);
        quizALL.addQuestionToQuiz(questionMY17);
        quizALL.addQuestionToQuiz(questionMY18);
        quizALL.addQuestionToQuiz(questionMY19);
        quizALL.addQuestionToQuiz(questionMY20);
        quizALL.addQuestionToQuiz(questionSP1);
        quizALL.addQuestionToQuiz(questionSP2);
        quizALL.addQuestionToQuiz(questionSP3);
        quizALL.addQuestionToQuiz(questionSP4);
        quizALL.addQuestionToQuiz(questionSP5);
        quizALL.addQuestionToQuiz(questionSP6);
        quizALL.addQuestionToQuiz(questionSP7);
        quizALL.addQuestionToQuiz(questionSP8);
        quizALL.addQuestionToQuiz(questionSP9);
        quizALL.addQuestionToQuiz(questionSP10);
        quizALL.addQuestionToQuiz(questionSP11);
        quizALL.addQuestionToQuiz(questionSP12);
        quizALL.addQuestionToQuiz(questionSP13);
        quizALL.addQuestionToQuiz(questionSP14);
        quizALL.addQuestionToQuiz(questionSP15);
        quizALL.addQuestionToQuiz(questionSP16);
        quizALL.addQuestionToQuiz(questionSP17);
        quizALL.addQuestionToQuiz(questionSP18);
        quizALL.addQuestionToQuiz(questionSP19);
        quizALL.addQuestionToQuiz(questionSP20);
        quizALL.addQuestionToQuiz(questionGE1);
        quizALL.addQuestionToQuiz(questionGE2);
        quizALL.addQuestionToQuiz(questionGE3);
        quizALL.addQuestionToQuiz(questionGE4);
        quizALL.addQuestionToQuiz(questionGE5);
        quizALL.addQuestionToQuiz(questionGE6);
        quizALL.addQuestionToQuiz(questionGE7);
        quizALL.addQuestionToQuiz(questionGE8);
        quizALL.addQuestionToQuiz(questionGE9);
        quizALL.addQuestionToQuiz(questionGE10);
        quizALL.addQuestionToQuiz(questionGE11);
        quizALL.addQuestionToQuiz(questionGE12);
        quizALL.addQuestionToQuiz(questionGE13);
        quizALL.addQuestionToQuiz(questionGE14);
        quizALL.addQuestionToQuiz(questionGE15);
        quizALL.addQuestionToQuiz(questionGE16);
        quizALL.addQuestionToQuiz(questionGE17);
        quizALL.addQuestionToQuiz(questionGE18);
        quizALL.addQuestionToQuiz(questionGE19);
        quizALL.addQuestionToQuiz(questionGE20);
        quizALL.addQuestionToQuiz(questionHI1);
        quizALL.addQuestionToQuiz(questionHI2);
        quizALL.addQuestionToQuiz(questionHI3);
        quizALL.addQuestionToQuiz(questionHI4);
        quizALL.addQuestionToQuiz(questionHI5);
        quizALL.addQuestionToQuiz(questionHI6);
        quizALL.addQuestionToQuiz(questionHI7);
        quizALL.addQuestionToQuiz(questionHI8);
        quizALL.addQuestionToQuiz(questionHI9);
        quizALL.addQuestionToQuiz(questionHI10);
        quizALL.addQuestionToQuiz(questionHI11);
        quizALL.addQuestionToQuiz(questionHI12);
        quizALL.addQuestionToQuiz(questionHI13);
        quizALL.addQuestionToQuiz(questionHI14);
        quizALL.addQuestionToQuiz(questionHI15);
        quizALL.addQuestionToQuiz(questionHI16);
        quizALL.addQuestionToQuiz(questionHI17);
        quizALL.addQuestionToQuiz(questionHI18);
        quizALL.addQuestionToQuiz(questionHI19);
        quizALL.addQuestionToQuiz(questionHI20);
        quizALL.addQuestionToQuiz(questionPO1);
        quizALL.addQuestionToQuiz(questionPO2);
        quizALL.addQuestionToQuiz(questionPO3);
        quizALL.addQuestionToQuiz(questionPO4);
        quizALL.addQuestionToQuiz(questionPO5);
        quizALL.addQuestionToQuiz(questionPO6);
        quizALL.addQuestionToQuiz(questionPO7);
        quizALL.addQuestionToQuiz(questionPO8);
        quizALL.addQuestionToQuiz(questionPO9);
        quizALL.addQuestionToQuiz(questionPO10);
        quizALL.addQuestionToQuiz(questionPO11);
        quizALL.addQuestionToQuiz(questionPO12);
        quizALL.addQuestionToQuiz(questionPO13);
        quizALL.addQuestionToQuiz(questionPO14);
        quizALL.addQuestionToQuiz(questionPO15);
        quizALL.addQuestionToQuiz(questionPO16);
        quizALL.addQuestionToQuiz(questionPO17);
        quizALL.addQuestionToQuiz(questionPO18);
        quizALL.addQuestionToQuiz(questionPO19);
        quizALL.addQuestionToQuiz(questionPO20);
        quizALL.addQuestionToQuiz(questionAR1);
        quizALL.addQuestionToQuiz(questionAR2);
        quizALL.addQuestionToQuiz(questionAR3);
        quizALL.addQuestionToQuiz(questionAR4);
        quizALL.addQuestionToQuiz(questionAR5);
        quizALL.addQuestionToQuiz(questionAR6);
        quizALL.addQuestionToQuiz(questionAR7);
        quizALL.addQuestionToQuiz(questionAR8);
        quizALL.addQuestionToQuiz(questionAR9);
        quizALL.addQuestionToQuiz(questionAR10);
        quizALL.addQuestionToQuiz(questionAR11);
        quizALL.addQuestionToQuiz(questionAR12);
        quizALL.addQuestionToQuiz(questionAR13);
        quizALL.addQuestionToQuiz(questionAR14);
        quizALL.addQuestionToQuiz(questionAR15);
        quizALL.addQuestionToQuiz(questionAR16);
        quizALL.addQuestionToQuiz(questionAR17);
        quizALL.addQuestionToQuiz(questionAR18);
        quizALL.addQuestionToQuiz(questionAR19);
        quizALL.addQuestionToQuiz(questionAR20);
        quizALL.addQuestionToQuiz(questionCE1);
        quizALL.addQuestionToQuiz(questionCE2);
        quizALL.addQuestionToQuiz(questionCE3);
        quizALL.addQuestionToQuiz(questionCE4);
        quizALL.addQuestionToQuiz(questionCE5);
        quizALL.addQuestionToQuiz(questionCE6);
        quizALL.addQuestionToQuiz(questionCE7);
        quizALL.addQuestionToQuiz(questionCE8);
        quizALL.addQuestionToQuiz(questionCE9);
        quizALL.addQuestionToQuiz(questionCE10);
        quizALL.addQuestionToQuiz(questionCE11);
        quizALL.addQuestionToQuiz(questionCE12);
        quizALL.addQuestionToQuiz(questionCE13);
        quizALL.addQuestionToQuiz(questionCE14);
        quizALL.addQuestionToQuiz(questionCE15);
        quizALL.addQuestionToQuiz(questionCE16);
        quizALL.addQuestionToQuiz(questionCE17);
        quizALL.addQuestionToQuiz(questionCE18);
        quizALL.addQuestionToQuiz(questionCE19);
        quizALL.addQuestionToQuiz(questionCE20);
        quizALL.addQuestionToQuiz(questionAN1);
        quizALL.addQuestionToQuiz(questionAN2);
        quizALL.addQuestionToQuiz(questionAN3);
        quizALL.addQuestionToQuiz(questionAN4);
        quizALL.addQuestionToQuiz(questionAN5);
        quizALL.addQuestionToQuiz(questionAN6);
        quizALL.addQuestionToQuiz(questionAN7);
        quizALL.addQuestionToQuiz(questionAN8);
        quizALL.addQuestionToQuiz(questionAN9);
        quizALL.addQuestionToQuiz(questionAN10);
        quizALL.addQuestionToQuiz(questionAN11);
        quizALL.addQuestionToQuiz(questionAN12);
        quizALL.addQuestionToQuiz(questionAN13);
        quizALL.addQuestionToQuiz(questionAN14);
        quizALL.addQuestionToQuiz(questionAN15);
        quizALL.addQuestionToQuiz(questionAN16);
        quizALL.addQuestionToQuiz(questionAN17);
        quizALL.addQuestionToQuiz(questionAN18);
        quizALL.addQuestionToQuiz(questionAN19);
        quizALL.addQuestionToQuiz(questionAN20);
        quizALL.addQuestionToQuiz(questionVE1);
        quizALL.addQuestionToQuiz(questionVE2);
        quizALL.addQuestionToQuiz(questionVE3);
        quizALL.addQuestionToQuiz(questionVE4);
        quizALL.addQuestionToQuiz(questionVE5);
        quizALL.addQuestionToQuiz(questionVE6);
        quizALL.addQuestionToQuiz(questionVE7);
        quizALL.addQuestionToQuiz(questionVE8);
        quizALL.addQuestionToQuiz(questionVE9);
        quizALL.addQuestionToQuiz(questionVE10);
        quizALL.addQuestionToQuiz(questionVE11);
        quizALL.addQuestionToQuiz(questionVE12);
        quizALL.addQuestionToQuiz(questionVE13);
        quizALL.addQuestionToQuiz(questionVE14);
        quizALL.addQuestionToQuiz(questionVE15);
        quizALL.addQuestionToQuiz(questionVE16);
        quizALL.addQuestionToQuiz(questionVE17);
        quizALL.addQuestionToQuiz(questionVE18);
        quizALL.addQuestionToQuiz(questionVE19);
        quizALL.addQuestionToQuiz(questionVE20);

        quizRepository.save(quizALL);

    }
}

